((c-mode . ((indent-tabs-mode . nil)
	    (c-default-style . "stroustrup")
	    (c-basic-offset . 2))
	 )
 (c++-mode . ((indent-tabs-mode . nil)
	      (c-default-style . "stroustrup")
	      (c-basic-offset . 2))
	   )
)
