name: Build Linux

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone Tree
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison clang lld llvm cmake libsdl2-ttf-dev libsdl2-image-dev libsdl2-dev
      - name: Build
        run: |
          cmake -S . -B build
          export MAKEFLAGS=-j$(nproc)
          cmake --build build --verbose
