name: Build

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone Tree
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Clone nxdk
        uses: actions/checkout@v2
        with:
          repository: XboxDev/nxdk
          path: nxdk
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison clang lld llvm clang-format
      - name: Check for new format errors
        run: |
          find . | grep -E '.*\.(c|cpp|h|hpp)$' | grep -Ev '(3rdparty|nxdk)/' | xargs clang-format --dry-run -Werror
      - name: Build
        run: |
          eval $(./nxdk/bin/activate -s)
          make -j$(nproc)
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: NevolutionX
          path: |
            *.iso
            bin
          if-no-files-found: error
